export const information = {
  heading:
    "GPK: An Efficient Special Character Input Method for Keyboards Using Glide",
  introduction:
    "A swipe-based input method for users with keyboard and mouse only to type special characters",
  title1: "ABSTRACT",
  content1:
    "We introduce an efficient input technique for special characters in keyboard environment. The technique, called GPK, consists of two steps for entering special characters. First, a user draws the special character on the keyboard by sliding over keys, and GPK recognizes the input character based on the input sequence. Second, the user can select the desired character from the predicted characters generated by GPK. In this paper, we present this input technique based on web browsers and a user study in order to compare the input efficiency of GPK with other methods of inputting special characters. This project can inspire future work of integrating this framework into word processors, document preparation systems and web environments.",
  title2: "Acknowledgement",
  content2:
    "I work with another ZJU undergraduate Xiyuan He on this project. The paper is submitted to CHI'19 Student Research Competition",
  title3: "MEDIA AND IMAGES",
  title4: "GPK: FREQUENTLY ASKED QUESTIONS",
  pdfhref: "",
  pdfcontent: "AVAILABLE LATER"
};

export const atlas = [
  {
    name: "pic1",
    content: "One example of using GPK",
    picsrc: require("@/assets/Portfolio/gpk/1.png")
  }
];

export const QA = [
  {
    question: "Does it work well and swift?",
    answer:
      "Yes. Currently, people use tying-based method like Markdown and LaTeX's mathematics mode, or selection-based method of choosing from a series of characters, to input special characters. Our method is significantly better in efficiency. Details can be seen inside the paper."
  },
  {
    question:
      "Now it just provided a web version, what if I want to use it ubiquitously?",
    answer:
      "With the same algorithm, it is easy to transplant GPK into other platforms, like a browser extension, a Word Macro, or a input method."
  }
];
